import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "@/providers/theme.provider";
import { Inter } from "next/font/google";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";

const calSans = localFont({
  src: "./fonts/CalSans SemiBold.woff",
  variable: "--font-cal",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${calSans.variable} ${inter.variable} font-sans antialiased`}
      >
        <TRPCReactProvider>
          <main className="h-full">{children}</main>
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
